stages:
  - install_node
  - unit_tests
  - flask_setup
  - e2e_tests

install_node_dependencies:
  stage: install_node
  image: node:latest
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

run_unit_tests:
  stage: unit_tests
  image: node:latest
  script:
    - npm test
  dependencies:
    - install_node_dependencies

flask_setup_and_run:
  stage: flask_setup
  image: python:3.9
  script:
    - apt-get update && apt-get install -y python3-venv python3-pip curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$PATH:$HOME/.local/bin"
    - poetry --version
    - poetry install
    - poetry run flask run --host=0.0.0.0 --port=5000 &
    - sleep 5  # Give Flask some time to start
    - curl --output /dev/null --silent --head --fail http://localhost:5000

run_cypress_tests:
  stage: e2e_tests
  image: cypress/base:latest
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium
  script:
    - CYPRESS_BASE_URL=http://localhost:5000 npx cypress run
  dependencies:
    - flask_setup_and_run
  artifacts:
    when: always
    reports:
      junit: cypress/results/*.xml
  allow_failure: false
