stages:
  - install_node
  - unit_tests
  - install_flask
  - start_flask
  - e2e_tests

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    - .cache/pypoetry/
    - .venv/  # Cache the virtual environment to speed up installs
    - /root/.local/

variables:
  FLASK_APP: app.py
  FLASK_ENV: development
  FLASK_RUN_PORT: 5000

install_node_dependencies:
  stage: install_node
  image: node:latest
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
  cache:
    paths:
      - node_modules/

run_unit_tests:
  stage: unit_tests
  image: node:latest
  script:
    - npm test
  dependencies:
    - install_node_dependencies

install_flask_dependencies:
  stage: install_flask
  image: python:3.9
  script:
    - whoami
    - echo $HOME
    - echo $PATH
    - apt-get update && apt-get install -y python3-venv python3-pip curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$PATH:$HOME/.local/bin"
    - poetry config virtualenvs.create false
    - poetry install
  cache:
    paths:
      - .venv/
      - .cache/pypoetry/
      - /root/.local/

start_flask_app:
  stage: start_flask
  image: python:3.9
  script:
    - export PATH="$PATH:$HOME/.local/bin"
    - echo $PATH
    - ls -la $HOME/.local/bin
    - ls -la $HOME/.local/
    - poetry --version
    - poetry run flask run --host=0.0.0.0 --port=5000 &
    - sleep 5  # Give Flask some time to start
    - curl --output /dev/null --silent --head --fail http://localhost:5000
  dependencies:
    - install_flask_dependencies

run_cypress_tests:
  stage: e2e_tests
  image: cypress/base:latest
  services:
    - name: selenium/standalone-chrome:latest
      alias: selenium
  script:
    - CYPRESS_BASE_URL=http://localhost:5000 npx cypress run
  dependencies:
    - start_flask_app
  artifacts:
    when: always
    reports:
      junit: cypress/results/*.xml
  allow_failure: false
