stages:
  - install_node
  - unit_tests
  - flask_setup
  - e2e_tests

cache:
  key: "${CI_COMMIT_REF_SLUG}"
  paths:
    - node_modules/
    - .cache/

install_node_dependencies:
  stage: install_node
  image: node:latest
  script:
    - npm install
  artifacts:
    paths:
      - node_modules/
      - .cache/ # Cypress
    expire_in: 1 hour

run_unit_tests:
  stage: unit_tests
  image: node:latest
  script:
    - npm test
  dependencies:
    - install_node_dependencies

flask_setup_and_run:
  stage: flask_setup
  image: python:3.9
  script:
    - apt-get update && apt-get install -y python3-venv python3-pip curl
    - curl -sSL https://install.python-poetry.org | python3 -
    - export PATH="$PATH:$HOME/.local/bin"
    - poetry --version
    - poetry install
    - poetry run flask run --host=0.0.0.0 --port=5000 &
    - sleep 5  # Give Flask some time to start
    - curl --output /dev/null --silent --head --fail http://127.0.0.1:5000/cf

run_cypress_tests:
  stage: e2e_tests
  image: cypress/base:latest
  script:
    - export CYPRESS_BASE_URL=http://localhost:5000
    - npx cypress run
  dependencies:
    - install_node_dependencies  # Ensure this includes install_node_dependencies
    - flask_setup_and_run